[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00C49A"
backgroundColor = "#0B1117"
secondaryBackgroundColor = "#111827"
textColor = "#F9FAFB"
font = "sans serif"
